# Validates the 16x16 ascii-art icons and emits src/icons_data.asm
ICONS = {
"INSPECT": """
................
.....kkkkk......
....kcwwcck.....
...kcwccccck....
...kccccccck....
...kccccccck....
...kccccccck....
....kccccck.....
.....kkkkkyk....
.........kyyk...
..........kyyk..
...........kyyk.
............kyk.
.............k..
................
................""",
"BULLDOZE": """
................
................
......kkkkk.....
......kcccyk....
......kcccyk....
.kk...kyyyyyk...
.kyk.kyyyyyyyk..
.kyykyyyyyyyyk..
.kyyyyyyyyyyyk..
.kykkkkkkkkkkk..
.kk.kdddddddk...
....kdkdkdkdk...
....kdddddddk...
.....kkkkkkk....
................
................""",
"ROAD": """
......kaak......
......kaak......
.....kaaaak.....
.....kaywak.....
.....kaywak.....
....kaaaaaak....
....kaaaaaak....
....kaaywaak....
...kaaaywaaak...
...kaaaaaaaak...
...kaaaaaaaak...
..kaaaaywaaaak..
..kaaaaywaaaak..
..kaaaaaaaaaak..
.kaaaaaaaaaaaak.
.kkkkkkkkkkkkkk.""",
"POWERLINE": """
.......kk.......
......knnk......
..kkkkknnkkkkk..
..kdddddddddddk.
..kkkkknnkkkkk..
.......knnk.....
......knnnnk....
......knknnk....
.....knk.knk....
.....knk..knk...
....knk...knk...
....knk....knk..
...knk.....knk..
...knk......knk.
..kkk.......kkk.
................""",
"ZONE_R": """
................
.......kk.......
......kGGk......
.....kGGGGk.....
....kGGGGGGk....
...kGGGGGGGGk...
..kkkkkkkkkkkk..
...kwwwwwwwwk...
...kwkkwwkkwk...
...kwkcwwkcwk...
...kwkkwwkkwk...
...kwwwnnwwwk...
...kwwwnnwwwk...
...kwwwnnwwwk...
...kkkkkkkkkk...
................""",
"ZONE_C": """
................
..kkkkkkkkkkkk..
..kbbbbbbbbbbk..
..kbwwwbbwwwbk..
..kkkkkkkkkkkk..
..kwrwrwrwrwrk..
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kwccwwwwccwk..
..kwccwwwwccwk..
..kwwwwkkwwwwk..
..kwccwkkwccwk..
..kwccwkkwccwk..
..kwwwwkkwwwwk..
..kkkkkkkkkkkk..
................""",
"ZONE_I": """
..........kk....
..........krk...
.........kwwk...
..........krk...
..........kwk...
..k...k...krk...
..kk..kk..kwk...
..kyk.kyk.krk...
..kyykkyykkwk...
..kyyyyyyyyyk...
..kyykyykyyyk...
..kyykyykyyyk...
..kyyyyyyyyyk...
..kYYYkkYYYYk...
..kkkkkkkkkkk...
................""",
"DEZONE": """
................
.kkkkkkkkkkkkkk.
.klllllllllllk..
.klrrllllllrrlk.
.kllrrllllrrllk.
.klllrrllrrlllk.
.kllllrrrrllllk.
.klllllrrlllllk.
.kllllrrrrllllk.
.klllrrllrrlllk.
.kllrrllllrrllk.
.klrrllllllrrlk.
.klllllllllllk..
.kkkkkkkkkkkkkk.
................
................""",
"POWER": """
.........kkk....
........kyyk....
.......kyyk.....
......kyyk......
.....kyyk.......
....kyyykkkk....
...kyyyyyyyk....
...kkkkyyyk.....
......kyyk......
.....kyyk.......
....kyyk........
...kyyk.........
...kyk..........
...kk...........
................
................""",
"WATER": """
.......kk.......
......kbbk......
......kbbk......
.....kbbbbk.....
.....kbbbbk.....
....kbbbbbbk....
...kbbwbbbbbk...
...kbwbbbbbbk...
..kbbwbbbbbbbk..
..kbbwbbbbbbbk..
..kbbbbbbbbbbk..
..kbbbbbbbbbbk..
...kbbbbbbbbk...
....kbbbbbbk....
.....kkkkkk.....
................""",
"SAFETY": """
................
....kkkkkkkk....
...kbbbbbbbbk...
..kbbbbbbbbbbk..
..kbbbyyyybbbk..
..kbbyyyyyybbk..
..kbbbyyyybbbk..
..kbbbbyybbbbk..
..kbbbbbbbbbbk..
...kbbbbbbbbk...
...kbbbbbbbbk...
....kbbbbbbk....
.....kbbbbk.....
......kbbk......
.......kk.......
................""",
"HEALTH": """
................
................
.....kkkkkk.....
.....kwwwwk.....
.....kwrrwk.....
..kkkkwrrwkkkk..
..kwwwwrrwwwwk..
..kwrrrrrrrrwk..
..kwrrrrrrrrwk..
..kwwwwrrwwwwk..
..kkkkwrrwkkkk..
.....kwrrwk.....
.....kwwwwk.....
.....kkkkkk.....
................
................""",
"EDU": """
................
................
.......kk.......
.....kkddkk.....
...kkddddddkk...
.kkddddddddddkk.
.kddddddddddddk.
..kkddddddddkky.
....kkddddkk..y.
....kddkkddk..y.
....kddddddk.kyk
....kddddddk.kyk
.....kkkkkk.....
................
................
................""",
"LEISURE": """
................
......kkkk......
....kkGGGGkk....
...kGGGGGGGGk...
..kGGGlGGGGGGk..
..kGGlGGGGGGGk..
..kGGGGGGGGhGk..
..kGGGGGGGhhGk..
...kGGGGGGGGk...
....kkkGGkkk....
......knnk......
......knnk......
......knnk......
....kknnnnkk....
................
................""",
"TREE": """
................
................
.......kk.......
......kGGk......
.....kGGGGk.....
....kGlGGGGk....
.....kGGGGk.....
....kGGGGGGk....
...kGlGGGGGGk...
....kkGGGGkk....
......knnk......
......knnk......
.....kknnkk.....
....kkkkkkkk....
................
................""",
"OVERLAY": """
................
.......kk.......
.....kkrrkk.....
...kkrrrrrrkk...
..krrrrrrrrrrk..
...kkrrrrrrkk...
..kyykkrrkkyyk..
..kyyyykkyyyyk..
...kkyyyyyykk...
..kbbkkyykkbbk..
..kbbbbkkbbbbk..
...kkbbbbbbkk...
.....kkbbkk.....
.......kk.......
................
................""",
"BUDGET": """
................
.....kkkkkk.....
...kkyyyyyykk...
..kyyyykkyyyyk..
..kyyykkkkkyyk..
.kyyykkykkyyyyk.
.kyyykkkyyyyyyk.
.kyyyykkkkyyyyk.
.kyyyyyykkkyyyk.
.kyyyykkykkyyyk.
..kyykkkkkyyyk..
..kyyyykkyyyyk..
...kkyyyyyykk...
.....kkkkkk.....
................
................""",
"MENU": """
................
................
................
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kkkkkkkkkkkk..
................
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kkkkkkkkkkkk..
................
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kkkkkkkkkkkk..
................
................""",
"CURSOR": """
k...............
kk..............
kwk.............
kwwk............
kwwwk...........
kwwwwk..........
kwwwwwk.........
kwwwwwwk........
kwwwwwwwk.......
kwwwwwwwwk......
kwwwwwkkkkk.....
kwwkwwk.........
kwk.kwwk........
kk..kwwk........
k....kwwk.......
.....kkk........""",
}
ORDER = ["INSPECT","BULLDOZE","ROAD","POWERLINE","ZONE_R","ZONE_C","ZONE_I","DEZONE",
         "POWER","WATER","SAFETY","HEALTH","EDU","LEISURE","TREE","OVERLAY","BUDGET","MENU","CURSOR"]
out = ["; generated by tools/icons_to_asm.py - 16x16 ascii-art icons",
       "; colour keys are decoded at start-up by icons_init (ui.asm)", "section .data", "icon_art:"]
for i, name in enumerate(ORDER):
    rows = ICONS[name].strip("\n").split("\n")
    assert len(rows) == 16, (name, len(rows))
    for r in rows:
        assert len(r) == 16, (name, r, len(r))
    out.append(f"ICON_{name} equ {i}")
    for r in rows:
        out.append(f'    db "{r}"')
out.append(f"ICON_COUNT equ {len(ORDER)}")
open("src/icons_data.asm", "w").write("\n".join(out) + "\n")
print("ok", len(ORDER))
